In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.1+cu121


In [ ]:
##Introduction to Tensors
###Creating Tensors
#Scalars
scalar=torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#Get tensor back as Python int
scalar.item()

7

In [ ]:
#vector
vector=torch.tensor([7,7])
vector
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#MATRIX
MATRIX=torch.tensor([[7,8],
                    [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR=torch.tensor([[[1,2,3],[3,6,9],[7,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [7, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [7, 4, 5]])

In [ ]:
TENSOR.reshape(3,3),
TENSOR.reshape(-1,3),
TENSOR.reshape(3,-1)

tensor([[1, 2, 3],
        [3, 6, 9],
        [7, 4, 5]])

In [ ]:
zeros=torch.zeros((2,3,4))


In [ ]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [ ]:
torch.randn(3,4)

tensor([[ 0.1094,  0.7440,  0.0950, -0.5654],
        [ 1.6426, -1.2715,  1.4254,  0.4031],
        [-0.3709,  0.2748,  1.1233, -0.7062]])

In [ ]:
torch.exp(TENSOR)

tensor([[[2.7183e+00, 7.3891e+00, 2.0086e+01],
         [2.0086e+01, 4.0343e+02, 8.1031e+03],
         [1.0966e+03, 5.4598e+01, 1.4841e+02]]])

In [ ]:
x=torch.tensor([[[3,4,5],[4,2,6],[2,7,9]]])
x

tensor([[[3, 4, 5],
         [4, 2, 6],
         [2, 7, 9]]])

In [ ]:
x+TENSOR,x-TENSOR,x*TENSOR,x/TENSOR

(tensor([[[ 4,  6,  8],
          [ 7,  8, 15],
          [ 9, 11, 14]]]),
 tensor([[[ 2,  2,  2],
          [ 1, -4, -3],
          [-5,  3,  4]]]),
 tensor([[[ 3,  8, 15],
          [12, 12, 54],
          [14, 28, 45]]]),
 tensor([[[3.0000, 2.0000, 1.6667],
          [1.3333, 0.3333, 0.6667],
          [0.2857, 1.7500, 1.8000]]]))

In [ ]:
torch.cat((x,TENSOR),dim=0)

tensor([[[3, 4, 5],
         [4, 2, 6],
         [2, 7, 9]],

        [[1, 2, 3],
         [3, 6, 9],
         [7, 4, 5]]])

In [ ]:
x==TENSOR

tensor([[[False, False, False],
         [False, False, False],
         [False, False, False]]])

In [ ]:
x.sum()


tensor(42)

In [ ]:
TENSOR.sum()

tensor(40)

In [ ]:
x.sum(), TENSOR.sum()

(tensor(42), tensor(40))

In [ ]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [ ]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [ ]:
before = id(b)
b= b + a
id(b) == before

False

In [ ]:
A = x.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [ ]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

In [ ]:
random=torch.rand(3,4)
random

tensor([[0.5280, 0.9121, 0.7058, 0.1926],
        [0.2455, 0.1214, 0.6119, 0.7772],
        [0.6698, 0.6102, 0.1866, 0.6592]])

In [ ]:
random_tensor=torch.rand(1,3,4)
random_tensor

tensor([[[0.7273, 0.5621, 0.4596, 0.3245],
         [0.7600, 0.6429, 0.3225, 0.1411],
         [0.1079, 0.2452, 0.0282, 0.9358]]])

In [ ]:
random_tensor.ndim

3

In [ ]:
imgsize_tensor=torch.rand(size=(3,224,224))
imgsize_tensor.shape,imgsize_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [ ]:
zeros*random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
zeros.dtype

torch.float32

In [ ]:
X=torch.arange(start=1,end=11,step=2)
X

tensor([1, 3, 5, 7, 9])

In [ ]:
Y=torch.zeros_like(X)
Y

tensor([0, 0, 0, 0, 0])

In [ ]:
float_32tensor=torch.tensor([3.0,6.0,9.0],
                            dtype=None,
                            device=None,
                            requires_grad=False)
float_32tensor

tensor([3., 6., 9.])

In [ ]:
float_32tensor.dtype

torch.float32